swagger: "2.0"
info:
  title: beego Test API
  description: beego has a very cool tools to autogenerate documents for your API
  version: 1.0.0
  termsOfService: http://beego.me/
  contact:
    email: astaxie@gmail.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
basePath: /v1
paths:
  /health/:
    get:
      tags:
      - health
      description: Health Controller
      responses:
        "200":
          description: '{string} service up and running!'
  /structs/:
    post:
      tags:
      - structs
      description: Create Struct
      parameters:
      - in: body
        name: body
        description: The struct content
        required: true
        schema:
          $ref: '#/definitions/groot.StructRequest'
      responses:
        "200":
          description: ""
          schema:
            $ref: '#/definitions/groot.Struct'
definitions:
  groot.Struct:
    title: Struct
    type: object
  groot.StructRequest:
    title: StructRequest
    type: object
tags:
- name: health
  description: |
    HealthController is controller for Health operation.
- name: structs
  description: |
    Operations about struct
